"""
Seeds ref.skills — a curated, cross-domain vocabulary spanning technical,
business, healthcare, education, retail/hospitality, construction,
manufacturing, agriculture, transport, government, media, beauty,
and banking skills. Extended 2026-10-05 to ~450 skills so every source's
postings (not just tech boards) have real match targets. `normalized_skill_name` is computed via
utils.normalize_name; `aliases` captures common abbreviations so early
rule-based extraction (Step 24) has something to match against immediately.
"""

from __future__ import annotations

from sqlalchemy import Connection, text

from .base import SeedResult, upsert_many
from .utils import normalize_name

# (skill_name, category_name, aliases, is_technology)
_SKILLS: list[tuple[str, str, list[str], bool]] = [
    # Programming Languages
    ("Python", "Programming Language", ["py"], True),
    ("JavaScript", "Programming Language", ["js", "ecmascript"], True),
    ("TypeScript", "Programming Language", ["ts"], True),
    ("Java", "Programming Language", [], True),
    ("Go", "Programming Language", ["golang"], True),
    ("Rust", "Programming Language", [], True),
    ("C", "Programming Language", [], True),
    ("C++", "Programming Language", ["cpp"], True),
    ("C#", "Programming Language", ["csharp", "dotnet c#"], True),
    ("Ruby", "Programming Language", [], True),
    ("PHP", "Programming Language", [], True),
    ("Swift", "Programming Language", [], True),
    ("Kotlin", "Programming Language", [], True),
    ("Scala", "Programming Language", [], True),
    ("R", "Programming Language", [], True),
    ("SQL", "Programming Language", [], True),
    ("Bash", "Programming Language", ["shell scripting"], True),
    ("Elixir", "Programming Language", [], True),
    ("Perl", "Programming Language", [], True),
    ("Dart", "Programming Language", [], True),
    # Frameworks
    ("React", "Framework", ["react.js", "reactjs"], True),
    ("Angular", "Framework", [], True),
    ("Vue.js", "Framework", ["vue"], True),
    ("Svelte", "Framework", [], True),
    ("Next.js", "Framework", ["nextjs"], True),
    ("Django", "Framework", [], True),
    ("Flask", "Framework", [], True),
    ("FastAPI", "Framework", [], True),
    ("Ruby on Rails", "Framework", ["rails"], True),
    ("Spring Boot", "Framework", ["spring"], True),
    ("Express.js", "Framework", ["express"], True),
    ("Laravel", "Framework", [], True),
    ("ASP.NET", "Framework", ["dotnet"], True),
    ("Node.js", "Framework", ["nodejs", "node"], True),
    ("Flutter", "Framework", [], True),
    ("React Native", "Framework", [], True),
    # Libraries
    ("Pandas", "Library", [], True),
    ("NumPy", "Library", [], True),
    ("PyTorch", "Library", [], True),
    ("TensorFlow", "Library", [], True),
    ("scikit-learn", "Library", ["sklearn"], True),
    ("Redux", "Library", [], True),
    ("jQuery", "Library", [], True),
    # Databases
    ("PostgreSQL", "Database", ["postgres"], True),
    ("MySQL", "Database", [], True),
    ("MongoDB", "Database", [], True),
    ("Redis", "Database", [], True),
    ("SQLite", "Database", [], True),
    ("Elasticsearch", "Database", [], True),
    ("Cassandra", "Database", [], True),
    ("DynamoDB", "Database", [], True),
    ("Oracle Database", "Database", ["oracle db"], True),
    ("Microsoft SQL Server", "Database", ["mssql", "sql server"], True),
    ("Snowflake", "Database", [], True),
    ("BigQuery", "Database", [], True),
    # Cloud Platforms
    ("AWS", "Cloud Platform", ["amazon web services"], True),
    ("Microsoft Azure", "Cloud Platform", ["azure"], True),
    ("Google Cloud Platform", "Cloud Platform", ["gcp"], True),
    ("Heroku", "Cloud Platform", [], True),
    ("DigitalOcean", "Cloud Platform", [], True),
    # DevOps / Infra
    ("Docker", "DevOps / Infrastructure Tool", [], True),
    ("Kubernetes", "DevOps / Infrastructure Tool", ["k8s"], True),
    ("Terraform", "DevOps / Infrastructure Tool", [], True),
    ("Ansible", "DevOps / Infrastructure Tool", [], True),
    ("Jenkins", "DevOps / Infrastructure Tool", [], True),
    ("GitHub Actions", "DevOps / Infrastructure Tool", [], True),
    ("GitLab CI/CD", "DevOps / Infrastructure Tool", [], True),
    ("CircleCI", "DevOps / Infrastructure Tool", [], True),
    ("Git", "DevOps / Infrastructure Tool", [], True),
    ("Prometheus", "DevOps / Infrastructure Tool", [], True),
    ("Grafana", "DevOps / Infrastructure Tool", [], True),
    ("Nginx", "DevOps / Infrastructure Tool", [], True),
    ("Apache Kafka", "DevOps / Infrastructure Tool", ["kafka"], True),
    ("RabbitMQ", "DevOps / Infrastructure Tool", [], True),
    # Operating Systems
    ("Linux", "Operating System", [], True),
    ("Windows Server", "Operating System", [], True),
    ("macOS", "Operating System", [], True),
    # AI / ML
    ("Machine Learning", "AI / ML", ["ml"], True),
    ("Deep Learning", "AI / ML", [], True),
    ("Natural Language Processing", "AI / ML", ["nlp"], True),
    ("Computer Vision", "AI / ML", [], True),
    ("Large Language Models", "AI / ML", ["llms"], True),
    ("MLOps", "AI / ML", [], True),
    ("Reinforcement Learning", "AI / ML", [], True),
    ("Explainable AI", "AI / ML", ["xai"], True),
    # Data & Analytics
    ("Data Analysis", "Data & Analytics", [], True),
    ("Data Visualization", "Data & Analytics", [], True),
    ("ETL", "Data & Analytics", [], True),
    ("Statistics", "Data & Analytics", [], True),
    ("A/B Testing", "Data & Analytics", [], True),
    ("Tableau", "Data & Analytics", [], True),
    ("Power BI", "Data & Analytics", [], True),
    ("Looker", "Data & Analytics", [], True),
    ("dbt", "Data & Analytics", [], True),
    ("Apache Spark", "Data & Analytics", ["spark"], True),
    ("Apache Airflow", "Data & Analytics", ["airflow"], True),
    # Design Tools
    ("Figma", "Design Tool", [], True),
    ("Adobe Photoshop", "Design Tool", ["photoshop"], True),
    ("Adobe Illustrator", "Design Tool", ["illustrator"], True),
    ("Sketch", "Design Tool", [], True),
    ("Adobe XD", "Design Tool", [], True),
    # PM Tools
    ("Jira", "Project Management Tool", [], True),
    ("Asana", "Project Management Tool", [], True),
    ("Trello", "Project Management Tool", [], True),
    ("Notion", "Project Management Tool", [], True),
    ("Confluence", "Project Management Tool", [], True),
    # Certifications
    ("AWS Certified Solutions Architect", "Certification", [], True),
    ("PMP", "Certification", ["project management professional"], True),
    ("CPA", "Certification", ["certified public accountant"], True),
    ("CISSP", "Certification", [], True),
    ("Scrum Master (CSM)", "Certification", ["csm"], True),
    ("Google Analytics Certification", "Certification", [], True),
    # Soft Skills
    ("Communication", "Soft Skill", [], False),
    ("Teamwork", "Soft Skill", ["collaboration"], False),
    ("Leadership", "Soft Skill", [], False),
    ("Problem Solving", "Soft Skill", [], False),
    ("Critical Thinking", "Soft Skill", [], False),
    ("Time Management", "Soft Skill", [], False),
    ("Adaptability", "Soft Skill", [], False),
    ("Creativity", "Soft Skill", [], False),
    ("Conflict Resolution", "Soft Skill", [], False),
    ("Emotional Intelligence", "Soft Skill", [], False),
    ("Mentoring", "Soft Skill", ["coaching"], False),
    ("Public Speaking", "Soft Skill", [], False),
    ("Negotiation", "Soft Skill", [], False),
    ("Attention to Detail", "Soft Skill", [], False),
    ("Cross-functional Collaboration", "Soft Skill", [], False),
    # Business Skills
    ("Project Management", "Business Skill", [], False),
    ("Agile", "Business Skill", ["scrum"], False),
    ("Product Strategy", "Business Skill", [], False),
    ("Stakeholder Management", "Business Skill", [], False),
    ("Budgeting", "Business Skill", [], False),
    ("Financial Modeling", "Business Skill", [], False),
    ("Sales Forecasting", "Business Skill", [], False),
    ("CRM Management", "Business Skill", [], False),
    ("SEO", "Business Skill", ["search engine optimization"], False),
    ("Content Strategy", "Business Skill", [], False),
    ("Copywriting", "Business Skill", [], False),
    ("Customer Relationship Management", "Business Skill", ["crm"], False),
    # Other Tools
    ("Salesforce", "Other Tool", [], True),
    ("HubSpot", "Other Tool", [], True),
    ("Zendesk", "Other Tool", [], True),
    ("Shopify", "Other Tool", [], True),
    ("WordPress", "Other Tool", [], True),
    ("Webflow", "Other Tool", [], True),
    ("Patient Care", "Healthcare Skill", [], False),
    ("Vital Signs Monitoring", "Healthcare Skill", [], False),
    ("Phlebotomy", "Healthcare Skill", [], False),
    ("Wound Care", "Healthcare Skill", [], False),
    ("CPR", "Healthcare Skill", ["cardiopulmonary resuscitation"], False),
    ("BLS", "Healthcare Skill", [], False),
    ("Advanced Cardiovascular Life Support", "Healthcare Skill", ["ACLS"], False),
    ("Medication Administration", "Healthcare Skill", [], False),
    ("Infection Control", "Healthcare Skill", [], False),
    ("Medical Coding", "Healthcare Skill", ["ICD-10", "medical billing"], False),
    ("Electronic Health Records", "Healthcare Skill", ["EHR", "EMR"], False),
    ("Triage", "Healthcare Skill", [], False),
    ("Immunization", "Healthcare Skill", [], False),
    ("Radiology", "Healthcare Skill", [], False),
    ("Laboratory Testing", "Healthcare Skill", [], False),
    ("Sterile Technique", "Healthcare Skill", [], False),
    ("Patient Counseling", "Healthcare Skill", [], False),
    ("Mental Health Care", "Healthcare Skill", [], False),
    ("Pediatric Care", "Healthcare Skill", [], False),
    ("Geriatric Care", "Healthcare Skill", [], False),
    ("Dental Hygiene", "Healthcare Skill", [], False),
    ("Dental Assisting", "Healthcare Skill", [], False),
    ("Pharmacology", "Healthcare Skill", [], False),
    ("Pharmacy Dispensing", "Healthcare Skill", [], False),
    ("Surgery Assisting", "Healthcare Skill", [], False),
    ("Anesthesia", "Healthcare Skill", [], False),
    ("Midwifery", "Healthcare Skill", [], False),
    ("Optometry", "Healthcare Skill", [], False),
    ("Physiotherapy", "Healthcare Skill", [], False),
    ("Speech Therapy", "Healthcare Skill", [], False),
    ("Occupational Therapy", "Healthcare Skill", [], False),
    ("Nutrition Counseling", "Healthcare Skill", [], False),
    ("First Aid", "Healthcare Skill", [], False),
    ("Patient Assessment", "Healthcare Skill", [], False),
    ("Clinical Documentation", "Healthcare Skill", [], False),
    ("Health Education", "Healthcare Skill", [], False),
    ("Lesson Planning", "Education Skill", [], False),
    ("Curriculum Development", "Education Skill", [], False),
    ("Classroom Management", "Education Skill", [], False),
    ("Student Assessment", "Education Skill", [], False),
    ("Differentiated Instruction", "Education Skill", [], False),
    ("Special Education", "Education Skill", [], False),
    ("Literacy Instruction", "Education Skill", [], False),
    ("Mathematics Teaching", "Education Skill", [], False),
    ("Science Teaching", "Education Skill", [], False),
    ("English Language Teaching", "Education Skill", [], False),
    ("Tutoring", "Education Skill", [], False),
    ("Adult Education", "Education Skill", [], False),
    ("Early Childhood Education", "Education Skill", [], False),
    ("Educational Technology", "Education Skill", [], False),
    ("Academic Advising", "Education Skill", [], False),
    ("Classroom Technology", "Education Skill", [], False),
    ("Instructional Design", "Education Skill", [], False),
    ("Test Administration", "Education Skill", [], False),
    ("Parent-Teacher Communication", "Education Skill", [], False),
    ("Customer Service", "Retail & Hospitality Skill", [], False),
    ("Cash Handling", "Retail & Hospitality Skill", [], False),
    ("Point of Sale", "Retail & Hospitality Skill", [], False),
    ("Stock Replenishment", "Retail & Hospitality Skill", [], False),
    ("Merchandising", "Retail & Hospitality Skill", [], False),
    ("Visual Merchandising", "Retail & Hospitality Skill", [], False),
    ("Inventory Management", "Retail & Hospitality Skill", [], False),
    ("Order Taking", "Retail & Hospitality Skill", [], False),
    ("Food Preparation", "Retail & Hospitality Skill", [], False),
    ("Food Safety", "Retail & Hospitality Skill", [], False),
    ("HACCP", "Retail & Hospitality Skill", ["Hazard Analysis Critical Control Point"], False),
    ("Cooking", "Retail & Hospitality Skill", [], False),
    ("Baking", "Retail & Hospitality Skill", [], False),
    ("Pastry", "Retail & Hospitality Skill", [], False),
    ("Baking & Pastry", "Retail & Hospitality Skill", [], False),
    ("Menu Planning", "Retail & Hospitality Skill", [], False),
    ("Barista Skills", "Retail & Hospitality Skill", [], False),
    ("Bartending", "Retail & Hospitality Skill", [], False),
    ("Food & Beverage Service", "Retail & Hospitality Skill", [], False),
    ("Room Service", "Retail & Hospitality Skill", [], False),
    ("Housekeeping", "Retail & Hospitality Skill", [], False),
    ("Guest Relations", "Retail & Hospitality Skill", [], False),
    ("Hotel Front Desk", "Retail & Hospitality Skill", [], False),
    ("Hospitality", "Retail & Hospitality Skill", [], False),
    ("Catering", "Retail & Hospitality Skill", [], False),
    ("Food Hygiene", "Retail & Hospitality Skill", [], False),
    ("Health and Safety", "Retail & Hospitality Skill", [], False),
    ("Kitchen Management", "Retail & Hospitality Skill", [], False),
    ("POS Systems", "Retail & Hospitality Skill", ["point of sale"], False),
    ("Barista Training", "Retail & Hospitality Skill", [], False),
    ("Carpentry", "Construction & Trades Skill", [], False),
    ("Electrical Wiring", "Construction & Trades Skill", [], False),
    ("Plumbing", "Construction & Trades Skill", [], False),
    ("Welding", "Construction & Trades Skill", [], False),
    ("Masonry", "Construction & Trades Skill", [], False),
    ("Bricklaying", "Construction & Trades Skill", [], False),
    ("Painting", "Construction & Trades Skill", [], False),
    ("Tiling", "Construction & Trades Skill", [], False),
    ("Roofing", "Construction & Trades Skill", [], False),
    ("Drywall Installation", "Construction & Trades Skill", [], False),
    ("Concrete Work", "Construction & Trades Skill", [], False),
    ("Carpentry Framing", "Construction & Trades Skill", [], False),
    ("Scaffold Erection", "Construction & Trades Skill", [], False),
    ("Heavy Equipment Operation", "Construction & Trades Skill", [], False),
    ("Forklift Operation", "Construction & Trades Skill", [], False),
    ("Crane Operation", "Construction & Trades Skill", [], False),
    ("HVAC", "Construction & Trades Skill", ["heating ventilation air conditioning"], False),
    ("HVAC Installation", "Construction & Trades Skill", [], False),
    ("Refrigeration", "Construction & Trades Skill", [], False),
    ("Auto Mechanics", "Construction & Trades Skill", [], False),
    ("Vehicle Maintenance", "Construction & Trades Skill", [], False),
    ("Auto Body Repair", "Construction & Trades Skill", [], False),
    ("Diesel Mechanics", "Construction & Trades Skill", [], False),
    ("Welding Fabrication", "Construction & Trades Skill", [], False),
    ("Soldering", "Construction & Trades Skill", [], False),
    ("Blueprint Reading", "Construction & Trades Skill", [], False),
    ("AutoCAD", "Construction & Trades Skill", [], False),
    ("Revit", "Construction & Trades Skill", [], False),
    ("Site Management", "Construction & Trades Skill", [], False),
    ("Quantity Surveying", "Construction & Trades Skill", [], False),
    ("Construction Safety", "Construction & Trades Skill", [], False),
    ("OSHA Safety", "Construction & Trades Skill", ["OSHA"], False),
    ("Building Inspection", "Construction & Trades Skill", [], False),
    ("Plumbing Installation", "Construction & Trades Skill", [], False),
    ("Electrical Safety", "Construction & Trades Skill", [], False),
    ("Machine Operation", "Manufacturing Skill", [], False),
    ("CNC Machining", "Manufacturing Skill", [], False),
    ("CNC Milling", "Manufacturing Skill", [], False),
    ("CNC Turning", "Manufacturing Skill", [], False),
    ("Assembly", "Manufacturing Skill", [], False),
    ("Quality Inspection", "Manufacturing Skill", [], False),
    ("Quality Control", "Manufacturing Skill", [], False),
    ("Lean Manufacturing", "Manufacturing Skill", [], False),
    ("Six Sigma", "Manufacturing Skill", [], False),
    ("ISO 9001", "Manufacturing Skill", [], False),
    ("Production Planning", "Manufacturing Skill", [], False),
    ("Plant Maintenance", "Manufacturing Skill", [], False),
    ("Calibration", "Manufacturing Skill", [], False),
    ("Robotic Operation", "Manufacturing Skill", [], False),
    ("Industrial Automation", "Manufacturing Skill", [], False),
    ("PLC Programming", "Manufacturing Skill", ["PLC"], False),
    ("G-code", "Manufacturing Skill", [], False),
    ("Stock Control", "Manufacturing Skill", [], False),
    ("Crop Farming", "Agriculture Skill", [], False),
    ("Livestock Management", "Agriculture Skill", [], False),
    ("Animal Husbandry", "Agriculture Skill", [], False),
    ("Dairy Farming", "Agriculture Skill", [], False),
    ("Poultry Farming", "Agriculture Skill", [], False),
    ("Fisheries", "Agriculture Skill", [], False),
    ("Aquaculture", "Agriculture Skill", [], False),
    ("Irrigation", "Agriculture Skill", [], False),
    ("Soil Management", "Agriculture Skill", [], False),
    ("Pest Control", "Agriculture Skill", [], False),
    ("Agricultural Machinery", "Agriculture Skill", [], False),
    ("Tractor Operation", "Agriculture Skill", [], False),
    ("Greenhouse Management", "Agriculture Skill", [], False),
    ("Organic Farming", "Agriculture Skill", [], False),
    ("Horticulture", "Agriculture Skill", [], False),
    ("Gardening", "Agriculture Skill", [], False),
    ("Veterinary Skills", "Agriculture Skill", [], False),
    ("Animal Restraint", "Agriculture Skill", [], False),
    ("Farm Management", "Agriculture Skill", [], False),
    ("Driving License", "Transport & Logistics Skill", [], False),
    ("Commercial Driving License", "Transport & Logistics Skill", ["CDL"], False),
    ("Truck Driving", "Transport & Logistics Skill", [], False),
    ("Bus Driving", "Transport & Logistics Skill", [], False),
    ("Delivery", "Transport & Logistics Skill", [], False),
    ("Route Planning", "Transport & Logistics Skill", [], False),
    ("Fleet Management", "Transport & Logistics Skill", [], False),
    ("Warehouse Operations", "Transport & Logistics Skill", [], False),
    ("Forklift Certification", "Transport & Logistics Skill", [], False),
    ("Logistics Coordination", "Transport & Logistics Skill", [], False),
    ("Supply Chain Coordination", "Transport & Logistics Skill", [], False),
    ("Inventory Control", "Transport & Logistics Skill", [], False),
    ("Freight Forwarding", "Transport & Logistics Skill", [], False),
    ("Port Operations", "Transport & Logistics Skill", [], False),
    ("Cargo Handling", "Transport & Logistics Skill", [], False),
    ("Pilot License", "Transport & Logistics Skill", ["PPL", "ATPL"], False),
    ("Aircraft Maintenance", "Transport & Logistics Skill", [], False),
    ("Cabin Crew Training", "Transport & Logistics Skill", [], False),
    ("Train Driving", "Transport & Logistics Skill", [], False),
    ("Maritime Navigation", "Transport & Logistics Skill", [], False),
    ("Ship Handling", "Transport & Logistics Skill", [], False),
    ("Public Administration", "Government & Public Sector Skill", [], False),
    ("Policy Analysis", "Government & Public Sector Skill", [], False),
    ("Government Accounting", "Government & Public Sector Skill", [], False),
    ("Tax Administration", "Government & Public Sector Skill", [], False),
    ("Customs Procedures", "Government & Public Sector Skill", [], False),
    ("Immigration Processing", "Government & Public Sector Skill", [], False),
    ("Public Procurement", "Government & Public Sector Skill", [], False),
    ("Records Management", "Government & Public Sector Skill", [], False),
    ("Community Policing", "Government & Public Sector Skill", [], False),
    ("Firefighting", "Government & Public Sector Skill", [], False),
    ("Emergency Response", "Government & Public Sector Skill", [], False),
    ("Disaster Management", "Government & Public Sector Skill", [], False),
    ("Social Work", "Government & Public Sector Skill", [], False),
    ("Child Protection", "Government & Public Sector Skill", [], False),
    ("Youth Development", "Government & Public Sector Skill", [], False),
    ("Urban Planning", "Government & Public Sector Skill", [], False),
    ("Environmental Regulation", "Government & Public Sector Skill", [], False),
    ("Inspection", "Government & Public Sector Skill", [], False),
    ("Regulatory Compliance", "Government & Public Sector Skill", [], False),
    ("Photography", "Media & Arts Skill", [], False),
    ("Video Editing", "Media & Arts Skill", [], False),
    ("Videography", "Media & Arts Skill", [], False),
    ("Camera Operation", "Media & Arts Skill", [], False),
    ("Photojournalism", "Media & Arts Skill", [], False),
    ("Writing", "Media & Arts Skill", [], False),
    ("Editing", "Media & Arts Skill", [], False),
    ("Proofreading", "Media & Arts Skill", [], False),
    ("Translation", "Media & Arts Skill", [], False),
    ("Interpreting", "Media & Arts Skill", [], False),
    ("Broadcasting", "Media & Arts Skill", [], False),
    ("Acting", "Media & Arts Skill", [], False),
    ("Music Production", "Media & Arts Skill", [], False),
    ("Playing Instruments", "Media & Arts Skill", [], False),
    ("Singing", "Media & Arts Skill", [], False),
    ("Dancing", "Media & Arts Skill", [], False),
    ("Event Planning", "Media & Arts Skill", [], False),
    ("DJ Skills", "Media & Arts Skill", [], False),
    ("Animation", "Media & Arts Skill", [], False),
    ("Voice Acting", "Media & Arts Skill", [], False),
    ("Content Creation", "Media & Arts Skill", [], False),
    ("Social Media Management", "Media & Arts Skill", [], False),
    ("Graphic Design", "Media & Arts Skill", [], False),
    ("Hairdressing", "Beauty & Wellness Skill", [], False),
    ("Barbering", "Beauty & Wellness Skill", [], False),
    ("Cosmetology", "Beauty & Wellness Skill", [], False),
    ("Skincare", "Beauty & Wellness Skill", [], False),
    ("Makeup Application", "Beauty & Wellness Skill", [], False),
    ("Nail Care", "Beauty & Wellness Skill", [], False),
    ("Massage Therapy", "Beauty & Wellness Skill", [], False),
    ("Spa Treatment", "Beauty & Wellness Skill", [], False),
    ("Esthetics", "Beauty & Wellness Skill", [], False),
    ("Wellness Coaching", "Beauty & Wellness Skill", [], False),
    ("Nutrition Coaching", "Beauty & Wellness Skill", [], False),
    ("Fitness Training", "Beauty & Wellness Skill", [], False),
    ("Yoga Instruction", "Beauty & Wellness Skill", [], False),
    ("Personal Training", "Beauty & Wellness Skill", [], False),
    ("Sports Coaching", "Beauty & Wellness Skill", [], False),
    ("Bookkeeping", "Banking & Finance Skill", [], False),
    ("Accounting", "Banking & Finance Skill", [], False),
    ("Financial Reporting", "Banking & Finance Skill", [], False),
    ("Auditing", "Banking & Finance Skill", [], False),
    ("Tax Preparation", "Banking & Finance Skill", [], False),
    ("Payroll", "Banking & Finance Skill", [], False),
    ("Banking Operations", "Banking & Finance Skill", [], False),
    ("Loan Processing", "Banking & Finance Skill", [], False),
    ("Credit Analysis", "Banking & Finance Skill", [], False),
    ("Risk Assessment", "Banking & Finance Skill", [], False),
    ("Insurance Underwriting", "Banking & Finance Skill", [], False),
    ("Claims Processing", "Banking & Finance Skill", [], False),
    ("Financial Advisory", "Banking & Finance Skill", [], False),
    ("Investment Analysis", "Banking & Finance Skill", [], False),
    ("Treasury Management", "Banking & Finance Skill", [], False),
    ("Xero", "Banking & Finance Skill", [], False),
    ("QuickBooks", "Banking & Finance Skill", [], False),
    ("SAP", "Banking & Finance Skill", [], False),
    ("Operations Management", "Business & Management Skill", [], False),
    ("Team Leadership", "Business & Management Skill", [], False),
    ("Strategic Planning", "Business & Management Skill", [], False),
    ("Business Development", "Business & Management Skill", [], False),
    ("Market Research", "Business & Management Skill", [], False),
    ("Sales", "Business & Management Skill", [], False),
    ("Conference Coordination", "Business & Management Skill", [], False),
    ("Supply Chain Management", "Business & Management Skill", [], False),
    ("Procurement", "Business & Management Skill", [], False),
    ("Vendor Management", "Business & Management Skill", [], False),
    ("Compliance Management", "Business & Management Skill", [], False),
    ("Quality Management", "Business & Management Skill", [], False),
    ("Change Management", "Business & Management Skill", [], False),
    ("Performance Management", "Business & Management Skill", [], False),
    ("Resource Planning", "Business & Management Skill", [], False),
    ("Risk Management", "Business & Management Skill", [], False),
    ("Budget Management", "Business & Management Skill", [], False),
    ("Contract Management", "Business & Management Skill", [], False),
    ("Facilities Management", "Business & Management Skill", [], False),
    ("Property Management", "Business & Management Skill", [], False),
    ("Real Estate Sales", "Business & Management Skill", [], False),
    ("CRM", "Business & Management Skill", ["customer relationship management"], False),
    ("ERP", "Business & Management Skill", ["enterprise resource planning"], False),
    ("Lean", "Business & Management Skill", [], False),
    ("Scrum", "Business & Management Skill", [], False),
    ("Kanban", "Business & Management Skill", [], False),
    ("Work Ethic", "Soft Skill", [], False),
    ("Reliability", "Soft Skill", [], False),
    ("Patience", "Soft Skill", [], False),
    ("Empathy", "Soft Skill", [], False),
    ("Customer Focus", "Soft Skill", [], False),
    ("Multitasking", "Soft Skill", [], False),
    ("Organization", "Soft Skill", [], False),
    ("Initiative", "Soft Skill", [], False),
    ("Resilience", "Soft Skill", [], False),
    ("Cultural Awareness", "Soft Skill", [], False),
]


def seed_skills(conn: Connection) -> SeedResult:
    category_ids = {
        r.category_name: r.skill_category_id
        for r in conn.execute(
            text("SELECT category_name, skill_category_id FROM ref.skill_categories")
        )
    }
    rows = []
    for name, category, aliases, is_tech in _SKILLS:
        rows.append(
            {
                "skill_name": name,
                "normalized_skill_name": normalize_name(name),
                "skill_category_id": category_ids[category],
                "aliases": aliases or None,
                "is_technology": is_tech,
                "embedding_ref": None,
            }
        )
    return upsert_many(
        conn,
        schema="ref",
        table_name="skills",
        rows=rows,
        conflict_cols=("normalized_skill_name",),
    )
